name: taxasge
description: Application de consultation des taxes fiscales de Guinée Équatoriale.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.3.0
  shared_preferences: ^2.5.3  # Mise à jour de la version
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.4  # Mise à jour de la version
  path_provider: ^2.1.5
  intl: ^0.20.2
  tflite_flutter: ^0.11.0
  firebase_core: ^3.13.0  # Mise à jour de la version
  firebase_messaging: ^15.2.5  # Mise à jour de la version
  firebase_analytics: ^11.4.5  # Mise à jour de la version
  connectivity_plus: ^6.1.3
  url_launcher: ^6.3.1  # Mise à jour de la version
  flutter_svg: ^2.0.17
  yaml: ^3.1.0  # Ajout du package yaml
  material_color_utilities: ^0.11.1  # Mise à jour de la version
  vm_service: ^14.3.1  # Mise à jour de la version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Mise à jour de la version
  mockito: ^5.4.4
  build_runner: ^2.4.10
  test: ^1.24.9
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/data/taxes.json
    - assets/data/taxes_schema.json
    - assets/images/
    - assets/icons/

flutter_test:
  assets:
    - test/test_assets/test_taxes.json